baseURL = 'https://farkasr215.github.io/melbournepredicts.github.io/'
languageCode = 'en-us'
title = 'Social Data Analysis and Visualization'
theme = "eureka"
publishDir = 'docs'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
